### ISSUE TITLE
Readme should mention the need to add the redirect uri message/output/slack/slackconnect.php

### ISSUE THREAD

**Issue by xow** [mchurchward/moodle-message_output_slack#1]

**Comment by mchurchward** [comment]
Not sure what you mean... The redirect URI is sent by the Slack button. If a user has not configured their Slack connection yet, they simply click the Slack button (see attachment). It sends the redirect information.
![screen shot 2017-05-19 at 9 21 20 am](https://cloud.githubusercontent.com/assets/819054/26249443/a30725dc-3c74-11e7-84af-5a006f3d9327.png)

**Comment by mchurchward** [comment]
Did you perhaps look at the "alpha" version? It had a config that didn't use the "Slack button". The version I released only had the Slack button.

**Comment by xow** [comment]
What I mean is: the instructions mention that you have to go to https://api.slack.com/apps to get your Client ID and client secret. But the instructions don't mention that you need to add "message/output/slack/slackconnect.php" as a redirect URI on api.slack.com

**Comment by mchurchward** [comment]
Gotcha.
This is now done - https://docs.moodle.org/33/en/Slack_message_processor
