### ISSUE TITLE
slackify_message breaks html

### ISSUE THREAD

**Issue by xow** [mchurchward/moodle-message_output_slack#2]
It breaks image tags and needs to unescape characters such as >

**Comment by mchurchward** [comment]
It intentionally does this, as I don't think anywhere in Moodle would allow image tags through the notification or messaging system. Is there actually a place where these are allowed?

**Comment by xow** [comment]
http://imgur.com/a/pywBw

Images are allowed. But my main concern, was that it is unreadable and confusing.

Note that this is a very simple forum post containing text (which is a common notification)
https://tracker.moodle.org/secure/attachment/55843/Screen%20Shot%202017-05-16%20at%2011.28.02%20am.png
The image was just the user's profile image. So every forum post will look like that unless we switch to text-based or work out a way to improve it

**Comment by mchurchward** [comment]
Yah. Okay. I was only testing with simple notifications. The forum kind of breaks that assumption. If I can't make them Slack friendly, I may have to switch it to text only.

**Comment by mchurchward** [comment]
I'm going to re-release so that it uses the text-only message. At least until I can somehow format HTML better for Slack (which will probably be never).
